version: "3"
services:
  composer:
    restart: "no"
    image: composer:1.5.2
    command: install
    volumes:
      - .:/app
      - .docker/data/composer:/opt/composer
    environment:
      COMPOSER_HOME: /opt/composer
  mysql:
    image: mysql:5.7
    volumes:
      - .docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
  php:
    build:
      context: .docker/php
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=2G
  nginx:
    image: nginx:1.13
    depends_on:
      - php
    links:
      - php
    volumes:
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
